[package]
name = "hiqlite"
version = "0.0.1"
edition = "2021"
rust-version = "1.75.0"
license = "Apache-2.0"
authors = ["Sebastian Dobe <sebastiandobe@mailbox.org"]
categories = ["database"]
keywords = ["database", "sql", "sqlite", "raft"]
description = "Hiqlite - highly-available, embeddable, raft-based SQLite"
readme = "README.md"
repository = "https://github.com/sebadob/hiqlite"

[package.metadata.docs.rs]
all-features = true

[[bin]]
name = "hiqlite"
path = "src/bin/main.rs"

[features]
default = ["auto-heal", "auto-heal-logs", "sqlite", "webpki-roots"]

auto-heal = []
auto-heal-logs = ["openraft/loosen-follower-log-revert"]
sqlite = []
io-uring = ["rocksdb/io-uring"]
jemalloc = ["rocksdb/jemalloc"]
webpki-roots = ["reqwest/rustls-tls-webpki-roots"]

[dependencies]
axum = { version = "0.7.5", features = ["http2", "tokio"] }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
bincode = "1.3.3"
byteorder = "1.4.3"
bytes = "1.6.0"
chrono = { version = "0.4.38", default-features = false, features = ["std", "clock", "now"] }
clap = { version = "4.1.11", features = ["derive", "env"] }
deadpool = { version = "0.12.1", features = ["rt_tokio_1"] }
fastwebsockets = { version = "0.8.0", features = ["upgrade", "with_axum", "unstable-split"] }
flume = "0.11.0"
getrandom = { version = "0.2.15", features = ["std"] }
hex = "0.4.3"
http-body-util = "0.1.2"
hyper = { version = "1.4.1", features = ["client", "http2"] }
hyper-util = { version = "0.1.6", features = ["client", "http2", "tokio"] }
openraft = { version = "0.9.13", features = ["serde", "storage-v2"] }
redb = "2.1.1"
reqwest = { version = "0.12", default-features = false, features = [
    "http2", "json", "rustls-tls"
] }
rocksdb = { version = "0.22.0", default-features = true, features = ["snappy"] }
rusqlite = { version = "0.31", features = ["backup", "bundled"] }
rustls = "0.23.5"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
serde_rusqlite = "0.35.0"
sha2 = { version = "0.10.8", features = ["asm"] }
thiserror = "1.0.61"
tokio = { version = "1.38.1", features = ["fs", "sync", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.0", features = ["env-filter"] }
uuid = { version = "1.8.0", features = ["v7"] }

# make minimal versions happy
lazy_static = "1.0.2"
lz4-sys = "1.9.5"

[build-dependencies]

[dev-dependencies]
tempfile = { version = "3.4.0" }
