[package]
name = "hiqlite"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
categories = ["database"]
keywords = ["database", "sql", "sqlite", "raft"]
description = "Hiqlite - highly-available, embeddable, raft-based SQLite"
readme = "../README.md"
repository = "https://github.com/sebadob/hiqlite"

[package.metadata.docs.rs]
all-features = true

[features]
#default = []
default = ["auto-heal", "backup", "sqlite"]
#default = ["auto-heal", "backup", "cache", "sqlite"]

sqlite = ["dep:deadpool", "dep:rusqlite", "dep:serde_rusqlite"]
cache = []
auto-heal = []
auto-heal-logs = ["openraft/loosen-follower-log-revert"]
backup = ["s3"]
s3 = ["backup", "dep:cryptr"]
io-uring = ["rocksdb/io-uring"]
jemalloc = ["rocksdb/jemalloc"]
webpki-roots = ["reqwest/rustls-tls-webpki-roots"]

[dependencies]
axum.workspace = true
axum-server.workspace = true
bincode.workspace = true
byteorder.workspace = true
bytes.workspace = true
chrono.workspace = true
cryptr = { workspace = true, optional = true }
deadpool = { workspace = true, optional = true }
fastwebsockets.workspace = true
flume.workspace = true
getrandom.workspace = true
hex.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
openraft.workspace = true
# TODO feature gate or completely remove for now
redb.workspace = true
reqwest.workspace = true
rocksdb.workspace = true
rusqlite = { workspace = true, optional = true }
rust-embed.workspace = true
# TODO do we need a tls feature?
rustls.workspace = true
serde.workspace = true
# TODO feature to make this available or simply always pull it in?
serde_json.workspace = true
serde_rusqlite = { workspace = true, optional = true }
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
uuid.workspace = true
# TODO can we feature gate here? probably a `tls` would need to pull these in then
# -> if not, try to use system trust store in TLS config builder?
webpki-roots.workspace = true

# make minimal versions happy
lazy_static.workspace = true
lz4-sys.workspace = true

[build-dependencies]

[dev-dependencies]
dotenvy = "0.15.7"
tracing-subscriber = { version = "0.3.0", features = ["env-filter"] }
